<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.1.0-alpha</Version>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>ImTK</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
  </ItemGroup>


  <ItemGroup>

  </ItemGroup>

</Project>
